sudo: required
services:
  - docker

before_install:
  - docker build -t 0hlov3s/google-sdk-terraform-alpine .
script:
  - docker images 0hlov3s/google-sdk-terraform-alpine

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push 0hlov3s/google-sdk-terraform-alpine;
    fi

